### ISSUE TITLE
Crash - attempt to place non-minecraft-elyra item into slot

### ISSUE THREAD

**Issue by CyberNewty** [TheIllusiveC4/CuriousElytra#20]
java.lang.NoSuchMethodError: top.theillusivec4.caelus.api.CaelusApi.canElytraFly(Lnet/minecraft/entity/LivingEntity;Lnet/minecraft/item/ItemStack;)Z
	at top.theillusivec4.curiouselytra.CuriousElytra.lambda$playerTick$1(CuriousElytra.java:98)
	at top.theillusivec4.curios.common.CuriosHelper.lambda$findEquippedCurio$3(CuriosHelper.java:117)
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:210)
	at top.theillusivec4.curios.common.CuriosHelper.findEquippedCurio(CuriosHelper.java:107)
	at top.theillusivec4.curiouselytra.CuriousElytra.playerTick(CuriousElytra.java:98)

**Comment by TheIllusiveC4** [comment]
Update Caelus to 2.1.3.0+.
